
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Lint build"
          command: |
            npm i
            npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: |
            npm i
            npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Analyze"
          command: npm audit

workflows:
  ci-pipeline-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
